apiVersion: v1
kind: Service
metadata:
  name: nodejs-example
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  nodejs_example_mapping
      prefix: /example/
      service: nodejs-example
spec:
  selector:
    app: nodejs-example
  ports:
  - port: 80
    name: http-nodejs-example
    targetPort: 3000