apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  prometheus-dashboard-mapping
      prefix: /dashboard/
      service: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 80
    name: hprometheus
    targetPort: 9090